import type { CardBodies } from './types';

/** Card bodies, cards 6–10. See bodies-1-5.ts for the authoring rules. */
export const BODIES_6_10: CardBodies = {
  C6: {
    hi: {
      kanoon: [
        'कोई भी बालिग़ औरत अपने अकेले नाम पर बैंक खाता खोल सकती है। पति या पिता की इजाज़त या साइन की कोई ज़रूरत क़ानून में नहीं है।',
        'RBI के KYC नियमों में आधार e-KYC काफ़ी है।',
        'PMJDY ज़ीरो-बैलेंस खाता: मिनिमम बैलेंस की कोई शर्त नहीं, जमा पर ब्याज, फ़्री RuPay कार्ड के साथ ₹2 लाख का दुर्घटना बीमा, योग्य खातों पर ₹10,000 तक ओवरड्राफ़्ट।',
        'इंडिया पोस्ट पेमेंट्स बैंक पोस्टमैन के ज़रिए घर पर बैंकिंग देती है — जहाँ बाहर निकलना मुश्किल हो, वहाँ काम आती है।',
        'हर खाते और डिपॉज़िट पर नॉमिनी बनाना आपका हक़ है।',
      ],
      asli: [
        '«बैंक में हस्बैंड के साइन चाहिए» — नहीं चाहिए। ऐसा कहने वाला बैंक ग़लत है; मैनेजर से बात करें या बैंक बदल दें। यह सही नहीं है।',
        'ATM कार्ड और PIN किसी और को दे देना ताकि वह खाता «चलाए» — अब आपके पैसे पर उसका कंट्रोल है। यह सही नहीं है।',
        'आपके नाम की सरकारी रक़म किसी और के खाते में आधार-सीड हो जाना। यह सही नहीं है।',
        '«फ़ोन तो वही रखते हैं» कह कर परिवार में OTP शेयर करना — OTP देना मतलब हाँ बोल देना। यह सही नहीं है।',
        'सिर्फ़ एक जॉइंट खाता होना जिसे असल में दूसरा ही चलाता हो। यह सही नहीं है।',
        'बचत समूह का लोन ऐसे खाते से गुज़रना जो आप देख या चला नहीं सकतीं। यह सही नहीं है।',
      ],
      sambhaal: [
        'आधार से PMJDY या पोस्ट-ऑफ़िस खाता खोलें, और उसमें अपना मोबाइल नंबर रजिस्टर करें।',
        'PIN और OTP परिवार में भी सीक्रेट। बैलेंस ख़ुद चेक करें — मिस्ड-कॉल बैंकिंग सिंपल फ़ोन पर भी चलती है।',
        'भरोसे के इंसान को नॉमिनी बनाएं।',
        'बैंक जाकर आधार–खाता DBT सीडिंग चेक करवाएं ताकि सरकारी पैसा आप तक ही पहुँचे।',
        'अपने नाम पर छोटी नियमित बचत — पोस्ट ऑफ़िस RD या महिला सम्मान सर्टिफ़िकेट।',
      ],
      ekKadam: 'कल बैंक जाकर अपने नाम का ज़ीरो-बैलेंस खाता खोलें।',
      authority: {
        office: 'बैंक ब्रांच → ब्रांच ग्रीवांस ऑफ़िसर → 30 दिन बाद RBI ओम्बड्समैन · बैंक मित्र · इंडिया पोस्ट पेमेंट्स बैंक',
        askFor: 'ब्रांच मैनेजर; ग्रीवांस ऑफ़िसर',
      },
    },
    hinglish: {
      kanoon: [
        'Koi bhi baalig aurat apne akele naam par bank account khol sakti hai. Pati ya pita ki ijaazat ya sign ki koi zaroorat kanoon mein nahin hai.',
        'RBI ke KYC niyamon mein Aadhaar e-KYC kaafi hai.',
        'PMJDY zero-balance khaata: minimum balance ki koi shart nahin, jama par byaaj, free RuPay card ke saath ₹2 lakh ka accident insurance, yogya khaton par ₹10,000 tak overdraft.',
        'India Post Payments Bank postman ke zariye ghar par banking deti hai — jahan bahar nikalna mushkil ho, wahan kaam aati hai.',
        'Har khaate aur deposit par nominee banana aapka haq hai.',
      ],
      asli: [
        '«Bank mein husband ke sign chahiye» — nahin chahiye. Aisa kehne waala bank galat hai; manager se baat karein ya bank badal dein. Yeh sahi nahin hai.',
        'ATM card aur PIN kisi aur ko de dena taaki woh khaata «chalaye» — ab aapke paise par uska control hai. Yeh sahi nahin hai.',
        'Aapke naam ki sarkari rakam kisi aur ke khaate mein Aadhaar-seed ho jaana. Yeh sahi nahin hai.',
        '«Phone toh wahi rakhte hain» keh kar parivaar mein OTP share karna — OTP dena matlab haan bol dena. Yeh sahi nahin hai.',
        'Sirf ek joint khaata hona jise asal mein doosra hi chalata ho. Yeh sahi nahin hai.',
        'Bachat samooh ka loan aise khaate se guzarna jo aap dekh ya chala nahin saktein. Yeh sahi nahin hai.',
      ],
      sambhaal: [
        'Aadhaar se PMJDY ya post-office khaata kholein, aur usmein apna mobile number register karein.',
        'PIN aur OTP parivaar mein bhi secret. Balance khud check karein — missed-call banking simple phone par bhi chalti hai.',
        'Bharose ke insaan ko nominee banayein.',
        'Bank jaakar Aadhaar–khaata DBT seeding check karwayein taaki sarkari paisa aap tak hi pahunche.',
        'Apne naam par chhoti niyamit bachat — post office RD ya Mahila Samman certificate.',
      ],
      ekKadam: 'Kal bank jaakar apne naam ka zero-balance khaata kholein.',
      authority: {
        office: 'Bank branch → Branch Grievance Officer → 30 din baad RBI Ombudsman · Bank Mitra · India Post Payments Bank',
        askFor: 'Branch Manager; Grievance Officer',
      },
    },
    en: {
      kanoon: [
        'Any adult woman can open a bank account in her sole name. No husband\'s or father\'s permission or signature is required by law.',
        'Under RBI\'s KYC rules, Aadhaar e-KYC is sufficient.',
        'A PMJDY zero-balance account has no minimum balance requirement, pays interest, includes ₹2 lakh accident cover with a free RuPay card, and offers an overdraft up to ₹10,000 on eligible accounts.',
        'India Post Payments Bank provides doorstep banking through the postman, which matters where leaving the house is difficult.',
        'Naming a nominee on every account and deposit is her right.',
      ],
      asli: [
        '"The bank needs your husband\'s signature." It does not. A bank saying so for her own single account is wrong; escalate to the manager or change banks. This is not right.',
        'Handing the ATM card and PIN to someone else to "operate" the account. Control of her money and her benefits passes with it. This is not right.',
        'A government payment in her name being Aadhaar-seeded to somebody else\'s account. This is not right.',
        'Sharing an OTP within the family because "he keeps the phone". Giving an OTP is giving consent. This is not right.',
        'Having only a joint account that in practice someone else operates. This is not right.',
        'A self-help group loan routed through an account she can neither see nor operate. This is not right.',
      ],
      sambhaal: [
        'Open a PMJDY or post office account with Aadhaar, and register her own mobile number on it.',
        'Keep PIN and OTP secret, including from family. Check the balance herself — missed-call banking works on a basic phone.',
        'Name a trusted person as nominee.',
        'Ask the branch to verify Aadhaar–account DBT seeding so benefits reach her.',
        'Start a small regular saving in her own name — a post office RD or a Mahila Samman certificate.',
      ],
      ekKadam: 'Go to a bank tomorrow and open a zero-balance account in your own name.',
      authority: {
        office: 'Bank branch → Branch Grievance Officer → RBI Ombudsman after 30 days · Bank Mitra · India Post Payments Bank',
        askFor: 'Branch Manager; Grievance Officer',
      },
    },
    numbers: ['1800-11-0001', '1800-180-1111', '14448'],
    portals: [
      { label: 'cms.rbi.org.in', href: 'https://cms.rbi.org.in' },
      { label: 'pmjdy.gov.in', href: 'https://pmjdy.gov.in' },
    ],
  },

  C7: {
    hi: {
      kanoon: [
        'यह कार्ड क़ानून से ज़्यादा प्रैक्टिकल है: बाक़ी हर कार्ड का हक़ तभी चलता है जब पहचान और सबूत हाथ में हों।',
        'आधार, PAN, मैरिज सर्टिफ़िकेट, बैंक पासबुक, बच्चों के बर्थ सर्टिफ़िकेट, राशन कार्ड और स्त्रीधन की लिस्ट — यही आपकी ताक़त हैं।',
        'कंट्रोल के लिए आपके काग़ज़ रोक लेना PWDVA धारा 3 की आर्थिक हिंसा का हिस्सा है।',
        'डिजीलॉकर में सरकारी विभाग से सीधे आए डिजिटल काग़ज़ असली के बराबर माने जाते हैं।',
      ],
      asli: [
        '«सब काग़ज़ हम संभाल के रखते हैं» — सारे ओरिजिनल हमेशा किसी और के पास रहना देखभाल नहीं, निर्भरता है। यह सही नहीं है।',
        'आधार या पासबुक किसी एम्प्लॉयर, ससुराल वाले या सूद वाले के पास «सिक्योरिटी» के नाम पर जमा करना। यह सही नहीं है।',
        'आपके आधार और बैंक रिकॉर्ड पर OTP वाला नंबर किसी और का होना। यह सही नहीं है।',
        'यह न पता होना कि मैरिज सर्टिफ़िकेट कहाँ है — या है भी या नहीं। यह सही नहीं है।',
        'आपके नाम पर सिम ले कर दूसरों का इस्तेमाल — उस नंबर पर जो होगा, ज़िम्मेदारी आपकी गिनी जाएगी। यह सही नहीं है।',
        '«रिकॉर्ड के लिए» ब्लैंक फ़ॉर्म या फ़ोटोकॉपियों पर साइन करना। यह सही नहीं है।',
      ],
      sambhaal: [
        'हर काग़ज़ की फ़ोटो लें; अपने ईमेल और डिजीलॉकर पर बैकअप करें। ईमेल बनाना मुफ़्त है और वह आपका है।',
        'ओरिजिनल वहाँ रखें जहाँ आप बिना इजाज़त पहुँच सकें।',
        'अपने नाम की अपनी सिम लें। आपकी ID पर कौन-कौन सी सिम चल रही हैं, संचार साथी पर देखें।',
        'आधार सुधार के लिए नज़दीकी आधार सेवा केंद्र या uidai.gov.in; हेल्पलाइन 1947।',
        'बच्चे का बर्थ सर्टिफ़िकेट नगर निगम या dc.crsorgi.gov.in से; मैरिज रजिस्ट्रेशन राज्य के e-District पोर्टल से।',
      ],
      ekKadam: 'हर काग़ज़ की फोटो लेकर अपने ईमेल पर भेज दें।',
      authority: {
        office: 'आधार सेवा केंद्र / CSC · नगर निगम या पंचायत (जन्म) · e-District (शादी) · काग़ज़ रोके जाएँ तो 181',
        askFor: 'आधार ऑपरेटर; CSC संचालक',
      },
    },
    hinglish: {
      kanoon: [
        'Yeh card kanoon se zyada practical hai: baaki har card ka haq tabhi chalta hai jab pehchaan aur saboot haath mein hon.',
        'Aadhaar, PAN, marriage certificate, bank passbook, bachchon ke birth certificate, ration card aur streedhan ki list — yahi aapki taakat hain.',
        'Control ke liye aapke kaagaz rok lena PWDVA dhara 3 ki aarthik hinsa ka hissa hai.',
        'DigiLocker mein sarkari vibhag se seedhe aaye digital kaagaz asli ke barabar maane jaate hain.',
      ],
      asli: [
        '«Sab kaagaz hum sambhal ke rakhte hain» — saare originals hamesha kisi aur ke paas rehna dekh-bhaal nahin, nirbharta hai. Yeh sahi nahin hai.',
        'Aadhaar ya passbook kisi employer, sasural waale ya sood waale ke paas «security» ke naam par jama karna. Yeh sahi nahin hai.',
        'Aapke Aadhaar aur bank record par OTP waala number kisi aur ka hona. Yeh sahi nahin hai.',
        'Yeh na pata hona ki marriage certificate kahan hai — ya hai bhi ya nahin. Yeh sahi nahin hai.',
        'Aapke naam par SIM le kar doosron ka istemal — us number par jo hoga, zimmedari aapki gini jayegi. Yeh sahi nahin hai.',
        '«Record ke liye» blank form ya photocopies par sign karna. Yeh sahi nahin hai.',
      ],
      sambhaal: [
        'Har kaagaz ki photo lein; apne email aur DigiLocker par backup karein. Email banana muft hai aur woh aapka hai.',
        'Originals wahan rakhein jahan aap bina ijaazat pahunch sakein.',
        'Apne naam ki apni SIM lein. Aapki ID par kaun-kaun si SIM chal rahi hain, Sanchar Saathi par dekhein.',
        'Aadhaar sudhaar ke liye nazdeeki Aadhaar Seva Kendra ya uidai.gov.in; helpline 1947.',
        'Bachche ka birth certificate nagar nigam ya dc.crsorgi.gov.in se; marriage registration rajya ke e-District portal se.',
      ],
      ekKadam: 'Har kaagaz ki photo lekar apne email par bhej dein.',
      authority: {
        office: 'Aadhaar Seva Kendra / CSC · Nagar nigam ya panchayat (janm) · e-District (shaadi) · Kaagaz roke jaayein toh 181',
        askFor: 'Aadhaar Operator; CSC VLE',
      },
    },
    en: {
      kanoon: [
        'This card is practical rather than statutory: every right on the other cards only becomes usable when identity and proof are within reach.',
        'Aadhaar, PAN, marriage certificate, bank passbook, children\'s birth certificates, ration card and the streedhan list are the toolkit.',
        'Withholding her documents in order to control her is part of economic abuse under PWDVA s.3.',
        'Documents pulled into DigiLocker directly from a government department are treated as equivalent to originals.',
      ],
      asli: [
        '"We keep all the papers safe." All the originals permanently in someone else\'s hands is not safekeeping, it is dependence. This is not right.',
        'Depositing Aadhaar or a passbook with an employer, in-law or moneylender as "security". This is not right.',
        'The OTP number on her Aadhaar and bank records belonging to someone else. This is not right.',
        'Not knowing where the marriage certificate is, or whether one exists at all. This is not right.',
        'A SIM taken in her name and used by others. Whatever happens on that number is counted as her responsibility. This is not right.',
        'Signing blank forms or photocopies "for the record". This is not right.',
      ],
      sambhaal: [
        'Photograph every document and back it up to her own email and DigiLocker. An email account is free, and it is hers.',
        'Keep originals somewhere she can reach without asking permission.',
        'Get a SIM in her own name, and check on Sanchar Saathi which SIMs are running on her ID.',
        'For Aadhaar corrections, use the nearest Aadhaar Seva Kendra or uidai.gov.in; helpline 1947.',
        'Get a child\'s birth certificate from the municipal office or dc.crsorgi.gov.in; register a marriage through the state e-District portal.',
      ],
      ekKadam: 'Photograph every document and email the photos to yourself.',
      authority: {
        office: 'Aadhaar Seva Kendra / CSC · Municipal or panchayat office (birth) · e-District (marriage) · 181 if documents are withheld',
        askFor: 'Aadhaar Operator; CSC VLE',
      },
    },
    numbers: ['1947', '181', '15100'],
    portals: [
      { label: 'uidai.gov.in', href: 'https://uidai.gov.in' },
      { label: 'digilocker.gov.in', href: 'https://digilocker.gov.in' },
      { label: 'sancharsaathi.gov.in', href: 'https://sancharsaathi.gov.in' },
    ],
  },

  C8: {
    hi: {
      kanoon: [
        'लीगल सर्विसेज़ अथॉरिटीज़ एक्ट 1987, धारा 12(c): हर औरत मुफ़्त क़ानूनी सहायता की हक़दार है। महिलाओं के लिए इनकम की कोई सीमा नहीं।',
        'यह संविधान के अनुच्छेद 39A से निकला हक़ है।',
        'मुफ़्त मतलब सच में मुफ़्त: पैनल वकील की फ़ीस, ड्राफ़्टिंग, कोर्ट फ़ीस, टाइपिंग, सर्टिफ़ाइड कॉपियाँ — सब ख़र्चा अथॉरिटी उठाती है, ट्रायल कोर्ट से सुप्रीम कोर्ट तक।',
        'कैसे मिलेगा: ज़िला कोर्ट में DLSA के फ़्रंट ऑफ़िस जाएँ; या 15100 पर कॉल करें; या बिना लॉगिन nalsa.gov.in से ऑनलाइन अप्लाई करें; या गाँव के लीगल एड क्लिनिक से।',
        'टेली-लॉ: 20 मिनट की मुफ़्त सलाह, उसी या अगले दिन, एक केस में तीन बार तक — और आप महिला वकील चुन सकती हैं।',
      ],
      asli: [
        '«वकील का ख़र्चा कौन उठाएगा?» — औरत के लिए सीधा जवाब: सरकार, क़ानून से। फ़ीस के डर से हक़ मत छोड़िए। यह सही नहीं है।',
        'कोर्ट गेट के दलालों को «सरकारी वकील दिलवाने» के पैसे देना — DLSA का फ़्रंट ऑफ़िस कोर्ट के अंदर ही है और मुफ़्त है। यह सही नहीं है।',
        '«मुफ़्त मतलब कमज़ोर वकील» मान लेना — पैनल वकील DLSA के प्रति जवाबदेह हैं, और बात न बने तो दूसरा वकील मांगा जा सकता है। यह सही नहीं है।',
        '«इनकम सर्टिफ़िकेट लगेगा» सोचना — महिलाओं की पात्रता कैटेगरी से है, इनकम से नहीं। यह सही नहीं है।',
        'एप्लिकेशन पर मिला डायरी नंबर खो देना — उसी से एप्लिकेशन ट्रैक होती है। यह सही नहीं है।',
        '«मैं पढ़-लिख नहीं सकती, फ़ॉर्म कैसे भरूँ» — पैरा-लीगल वॉलंटियर इसी काम के लिए हैं। यह सही नहीं है।',
      ],
      sambhaal: [
        'आज ही फ़ोन में दो नंबर सेव करें: 15100 (मुफ़्त वकील) और 181 (महिला हेल्पलाइन)।',
        'लड़ाई से पहले सलाह: नज़दीकी CSC पर टेली-लॉ, या 14454। मुफ़्त, प्राइवेट, और महिला वकील चुन सकती हैं।',
        'केस के लिए DLSA एप्लिकेशन दें, डायरी नंबर नोट करें और ट्रैक करें।',
        'समझौता हो सकने वाले मामलों में DLSA से अगली लोक अदालत के बारे में पूछें।',
        'NALSA मोबाइल ऐप से फ़ोन से ही एप्लिकेशन फ़ाइल और ट्रैक हो जाती है।',
      ],
      ekKadam: 'आज फ़ोन में दो नंबर सेव करें — 15100 और 181।',
      authority: {
        office: 'DLSA फ़्रंट ऑफ़िस (ज़िला कोर्ट के अंदर) · लीगल एड क्लिनिक / पैरा-लीगल वॉलंटियर · टेली-लॉ के लिए CSC',
        askFor: 'DLSA फ़्रंट ऑफ़िस; पैरा-लीगल वॉलंटियर',
      },
    },
    hinglish: {
      kanoon: [
        'Legal Services Authorities Act 1987, dhara 12(c): har aurat muft kanooni sahayata ki haqdaar hai. Mahilaon ke liye income ki koi seema nahin.',
        'Yeh Samvidhan ke Article 39A se nikla haq hai.',
        'Muft matlab sach mein muft: panel vakil ki fees, drafting, court fees, typing, certified copies — sab kharcha authority uthati hai, trial court se Supreme Court tak.',
        'Kaise milega: zila court mein DLSA ke front office jaayein; ya 15100 par call karein; ya bina login nalsa.gov.in se online apply karein; ya gaon ke Legal Aid Clinic se.',
        'Tele-Law: 20 minute ki muft salaah, usi ya agle din, ek case mein teen baar tak — aur aap mahila vakil chun sakti hain.',
      ],
      asli: [
        '«Vakil ka kharcha kaun uthayega?» — aurat ke liye seedha jawab: sarkar, kanoon se. Fees ke dar se haq mat chhodiye. Yeh sahi nahin hai.',
        'Court gate ke dalalon ko «sarkari vakil dilwane» ke paise dena — DLSA ka front office court ke andar hi hai aur muft hai. Yeh sahi nahin hai.',
        '«Muft matlab kamzor vakil» maan lena — panel vakil DLSA ke prati jawabdeh hain, aur baat na bane toh doosra vakil maanga ja sakta hai. Yeh sahi nahin hai.',
        '«Income certificate lagega» sochna — mahilaon ki paatrata category se hai, income se nahin. Yeh sahi nahin hai.',
        'Application par mila Diary Number kho dena — usi se application track hoti hai. Yeh sahi nahin hai.',
        '«Main padh-likh nahin sakti, form kaise bharoon» — Para-Legal Volunteer isi kaam ke liye hain. Yeh sahi nahin hai.',
      ],
      sambhaal: [
        'Aaj hi phone mein do number save karein: 15100 (muft vakil) aur 181 (mahila helpline).',
        'Ladai se pehle salaah: nazdeeki CSC par Tele-Law, ya 14454. Muft, private, aur mahila vakil chun sakti hain.',
        'Case ke liye DLSA application dein, Diary Number note karein aur track karein.',
        'Samjhauta ho sakne waale maamlon mein DLSA se agli Lok Adalat ke baare mein poochhein.',
        'NALSA mobile app se phone se hi application file aur track ho jaati hai.',
      ],
      ekKadam: 'Aaj phone mein do number save karein — 15100 aur 181.',
      authority: {
        office: 'DLSA front office (zila court ke andar) · Legal Aid Clinic / Para-Legal Volunteer · Tele-Law ke liye CSC',
        askFor: 'DLSA Front Office; Para-Legal Volunteer',
      },
    },
    en: {
      kanoon: [
        'Legal Services Authorities Act 1987, s.12(c): every woman is entitled to free legal aid. There is no income limit for women.',
        'The entitlement flows from Article 39A of the Constitution.',
        'Free means genuinely free: panel lawyer\'s fees, drafting, court fees, typing and certified copies are all borne by the legal services authority, from trial court to Supreme Court.',
        'How to get it: walk into the DLSA front office inside the district court; or call 15100; or apply online at nalsa.gov.in with no login; or go to a village legal aid clinic.',
        'Tele-Law gives 20 minutes of free advice, same or next day, up to three times per matter — and a woman lawyer can be requested.',
      ],
      asli: [
        '"Who will pay for a lawyer?" For a woman the answer is: the state, by law. Do not give up a right out of fear of fees. This is not right.',
        'Paying touts at the court gate to "arrange a government lawyer". The DLSA front office is inside the court and it is free. This is not right.',
        'Assuming free means a weak lawyer. Panel lawyers are accountable to the DLSA, and another can be requested if it is not working. This is not right.',
        'Believing an income certificate is needed. Women qualify by category, not by income. This is not right.',
        'Losing the diary number issued with the application. That number is how the application is tracked. This is not right.',
        '"I can\'t read or write, how do I fill the form?" Para-Legal Volunteers exist precisely for this. This is not right.',
      ],
      sambhaal: [
        'Save two numbers in the phone today: 15100 for a free lawyer and 181 for the women\'s helpline.',
        'Get advice before a dispute: Tele-Law at the nearest CSC, or 14454. Free, private, and a woman lawyer can be requested.',
        'For a case, file a DLSA application, note the diary number and track it.',
        'For matters that can settle, ask DLSA about the next Lok Adalat.',
        'The NALSA mobile app files and tracks an application from the phone itself.',
      ],
      ekKadam: 'Save two numbers in your phone today — 15100 and 181.',
      authority: {
        office: 'DLSA front office (inside the district court) · Legal Aid Clinic / Para-Legal Volunteer · CSC for Tele-Law',
        askFor: 'DLSA Front Office; Para-Legal Volunteer',
      },
    },
    numbers: ['15100', '14454'],
    portals: [
      { label: 'nalsa.gov.in', href: 'https://nalsa.gov.in' },
      { label: 'tele-law.in', href: 'https://tele-law.in' },
      { label: 'sclsc.gov.in', href: 'https://sclsc.gov.in' },
    ],
  },

  C9: {
    hi: {
      kanoon: [
        'हिंदू उत्तराधिकार अधिनियम, धाराएँ 8–10: विधवा अपने पति की क्लास I वारिस है। पति की संपत्ति में वह बच्चों के बराबर हिस्सेदार है, और उसका हिस्सा बेटों को नहीं दिया जा सकता।',
        'जो संपत्ति विरासत में मिल कर आपकी हो गई, वह पूरी तरह आपकी है (HSA धारा 14)। दूसरी शादी करने से पहले से मिली संपत्ति वापस नहीं जाती।',
        'सोग के दिनों में दबाव या बहकावे में साइन करवाया गया हक़-त्याग पेपर रद्द करवाया जा सकता है। ऐसे पेपर मौत के बाद के हफ़्तों में ही आते हैं।',
        'कुछ हालात में ससुर की संपत्ति से गुज़ारा भत्ता भी मिल सकता है (HAMA धारा 19)।',
        'पेंशन: IGNWPS के तहत BPL विधवा, 40+ उम्र को केंद्र से हर महीने पैसा मिलता है, और राज्य अपना टॉप-अप जोड़ते हैं। कई राज्य योजनाएँ 18 साल से शुरू होती हैं।',
      ],
      asli: [
        'मौत के कुछ हफ़्तों बाद «फ़ॉर्मैलिटीज़ के लिए» लाया गया हक़-त्याग पेपर — DLSA की मुफ़्त सलाह से पहले साइन न करें। एक बार साइन हुआ तो पलटना बहुत मुश्किल। यह सही नहीं है।',
        '«विधवा का हिस्सा बेटों को जाता है» — आप ख़ुद अपने हक़ से क्लास I वारिस हैं। यह सही नहीं है।',
        '«दोबारा शादी की तो सब वापस» — जो पहले मिल चुका, वह आपका रहता है। यह सही नहीं है।',
        'सोग के वक़्त «थोड़े दिन के लिए» घर से हटा देना — साझा घर में रहने का हक़ विधवा पर भी लागू है। यह सही नहीं है।',
        'पेंशन «दिलवाने» के लिए कमीशन मांगने वाले एजेंट — पंचायत या ब्लॉक ऑफ़िस में आवेदन मुफ़्त है। यह सही नहीं है।',
        'पति के बैंक, बीमा और EPF काग़ज़ रिश्तेदारों को «प्रोसेस करवाने» दे देना — क्लेम आपके हैं, आप ही करें। यह सही नहीं है।',
      ],
      sambhaal: [
        'डेथ सर्टिफ़िकेट की 8–10 पक्की कॉपियाँ तुरंत लें — नगर निगम या पंचायत से।',
        'लिस्ट बनाएं क्या-क्या है: बैंक खाते, बीमा, EPF, ज़मीन, घर। फिर नॉमिनी या वारिस बन कर क्लेम करें।',
        'लीगल-हेयर या सक्सेशन सर्टिफ़िकेट DLSA की मदद से मुफ़्त बनवाएं।',
        'विधवा पेंशन का आवेदन ग्राम पंचायत, ब्लॉक ऑफ़िस या UMANG पर करें; रसीद संभालें।',
        'घर और ज़मीन के रिकॉर्ड में अपना नाम चढ़वाएं।',
      ],
      ekKadam: 'मौत के सरकारी काग़ज़ की 8–10 पक्की कॉपियाँ ले लें।',
      authority: {
        office: 'ग्राम पंचायत / ब्लॉक ऑफ़िस · ज़िला समाज कल्याण ऑफ़िस · नगर निगम (डेथ सर्टिफ़िकेट) · DLSA',
        askFor: 'BDO / पंचायत सचिव; समाज कल्याण अधिकारी',
      },
    },
    hinglish: {
      kanoon: [
        'Hindu Succession Act, dharaein 8–10: vidhwa apne pati ki Class I waaris hai. Pati ki sampatti mein woh bachchon ke barabar hissedar hai, aur uska hissa beton ko nahin diya ja sakta.',
        'Jo sampatti virasat mein mil kar aapki ho gayi, woh poori tarah aapki hai (HSA dhara 14). Doosri shaadi karne se pehle se mili sampatti wapas nahin jaati.',
        'Sog ke dinon mein dabav ya bahkave mein sign karwaya gaya haq-tyag paper radd karwaya ja sakta hai. Aise paper maut ke baad ke hafton mein hi aate hain.',
        'Kuchh haalaat mein sasur ki sampatti se guzara bhatta bhi mil sakta hai (HAMA dhara 19).',
        'Pension: IGNWPS ke tehat BPL vidhwa, 40+ umar ko kendra se har mahine paisa milta hai, aur rajya apna top-up jodte hain. Kai rajya yojanayein 18 saal se shuru hoti hain.',
      ],
      asli: [
        'Maut ke kuchh hafton baad «formalities ke liye» laya gaya haq-tyag paper — DLSA ki muft salaah se pehle sign na karein. Ek baar sign hua toh palatna bahut mushkil. Yeh sahi nahin hai.',
        '«Vidhwa ka hissa beton ko jaata hai» — aap khud apne haq se Class I waaris hain. Yeh sahi nahin hai.',
        '«Dobara shaadi ki toh sab wapas» — jo pehle mil chuka, woh aapka rehta hai. Yeh sahi nahin hai.',
        'Sog ke waqt «thode din ke liye» ghar se hata dena — saajha ghar mein rehne ka haq vidhwa par bhi laagu hai. Yeh sahi nahin hai.',
        'Pension «dilwane» ke liye commission maangne waale agents — panchayat ya block office mein aavedan muft hai. Yeh sahi nahin hai.',
        'Pati ke bank, beema aur EPF kaagaz rishtedaaron ko «process karwane» de dena — claim aapke hain, aap hi karein. Yeh sahi nahin hai.',
      ],
      sambhaal: [
        'Death certificate ki 8–10 pakki copies turant lein — nagar nigam ya panchayat se.',
        'List banayein kya-kya hai: bank khaate, beema, EPF, zameen, ghar. Phir nominee ya waaris ban kar claim karein.',
        'Legal-heir ya succession certificate DLSA ki madad se muft banwayein.',
        'Vidhwa pension ka aavedan gram panchayat, block office ya UMANG par karein; raseed sambhaalein.',
        'Ghar aur zameen ke record mein apna naam chadhwayein.',
      ],
      ekKadam: 'Maut ke sarkari kaagaz ki 8–10 pakki copies le lein.',
      authority: {
        office: 'Gram Panchayat / Block office · Zila Samaj Kalyan office · Nagar nigam (death certificate) · DLSA',
        askFor: 'BDO / Panchayat Secretary; Social Welfare Officer',
      },
    },
    en: {
      kanoon: [
        'Hindu Succession Act, ss.8–10: a widow is a Class I heir of her husband. She shares his property equally with the children, and her share cannot be given to the sons.',
        'Property that has vested in her by inheritance is absolutely hers (HSA s.14). Remarriage does not take back what already vested.',
        'A relinquishment signed under pressure or misrepresentation during mourning can be set aside. Such papers appear in exactly those weeks after a death.',
        'In some circumstances maintenance is also available from the father-in-law\'s estate (HAMA s.19).',
        'Pension: under IGNWPS a BPL widow aged 40 and above receives a monthly central payment, with states adding their own top-up. Many state schemes begin at 18.',
      ],
      asli: [
        'A relinquishment brought "for the formalities" a few weeks after the death. Do not sign before free DLSA advice — once signed it is very hard to undo. This is not right.',
        '"A widow\'s share goes to the sons." She is a Class I heir in her own right. This is not right.',
        '"If you remarry it all goes back." What has already vested stays hers. This is not right.',
        'Moving her out of the house "just for a few days" during mourning. The right to reside in a shared household applies to a widow too. This is not right.',
        'Agents asking for a commission to "arrange" a pension. Applying at the panchayat or block office is free. This is not right.',
        'Letting relatives "process" the husband\'s bank, insurance and EPF papers. The nominee and heir claims are hers to make. This is not right.',
      ],
      sambhaal: [
        'Obtain 8–10 certified copies of the death certificate immediately, from the municipal office or panchayat.',
        'List what exists: bank accounts, insurance, EPF, land, house. Then claim as nominee or heir.',
        'Get a legal-heir or succession certificate free, with DLSA\'s help.',
        'Apply for the widow pension at the gram panchayat, block office or on UMANG, and keep the receipt.',
        'Get her name entered in the house and land records.',
      ],
      ekKadam: 'Get 8–10 certified copies of the death certificate.',
      authority: {
        office: 'Gram Panchayat / Block Development Office · District Social Welfare office · Municipal office (death certificate) · DLSA',
        askFor: 'BDO / Panchayat Secretary; Social Welfare Officer',
      },
    },
    numbers: ['15100', '181', '14454'],
    portals: [
      { label: 'myscheme.gov.in', href: 'https://myscheme.gov.in' },
      { label: 'scourtapp.nic.in/lsams', href: 'https://scourtapp.nic.in/lsams' },
    ],
  },

  C10: {
    hi: {
      kanoon: [
        'पति के पर्सनल लोन की ज़िम्मेदारी पत्नी पर अपने-आप नहीं आती। कॉन्ट्रैक्ट सिर्फ़ साइन करने वालों को बांधता है।',
        'गारंटी तभी है जब आपने सच में गारंटर के तौर पर साइन किया हो (Contract Act धारा 126) — और दबाव या धोखे से लिया गया साइन रद्द करवाया जा सकता है (धाराएँ 15–19)।',
        'RBI के नियम बैंकों, NBFCs और उनके रिकवरी एजेंटों पर लागू हैं: कॉल या विज़िट सिर्फ़ सुबह 8 से शाम 7 तक, धमकी या बेइज़्ज़ती नहीं, और एजेंट को अपना और कंपनी का नाम बताना होगा।',
        'लेंडर के ग्रीवांस ऑफ़िसर को लिखित शिकायत के 30 दिन में हल न हो, तो cms.rbi.org.in पर मुफ़्त शिकायत करें। रिकवरी-एजेंट हैरेसमेंट इसकी लिस्ट में साफ़ लिखा है।',
        'एजेंट की धमकी, घर में घुसना या मार-पीट लोन से अलग, सीधा पुलिस का मामला है — 112।',
      ],
      asli: [
        'ब्लैंक पेपर, अधूरा फ़ॉर्म, या जो पढ़ न सकें — उस पर कभी साइन नहीं। «बस साइन कर दो, फ़ॉर्मैलिटी है» से ही गारंटी बना दी जाती है। यह सही नहीं है।',
        '«सिर्फ़ काग़ज़ पर» गारंटर या को-बॉरोअर बनना — ज़िम्मेदारी काग़ज़ पर ही तो रहती है। यह सही नहीं है।',
        'किसी और के लोन के लिए अपना आधार और फ़ोटो दे देना। यह सही नहीं है।',
        'बचत समूह का लोन आपके नाम पर और इस्तेमाल दूसरों का — डिफ़ॉल्ट आपके रिकॉर्ड पर बैठता है। यह सही नहीं है।',
        'रात को कॉल, बार-बार घर आना, पड़ोसियों के सामने बेइज़्ज़ती — यह सब नियम तोड़ना है, आदत नहीं। हर एक की रिपोर्ट हो सकती है। यह सही नहीं है।',
        'ऐसे लोन ऐप जो कॉन्टैक्ट्स और फ़ोटो का एक्सेस मांगें — यह ब्लैकमेल का जाना-पहचाना पैटर्न है। यह सही नहीं है।',
        '«लोन क्लोज़र वेरिफ़ाई करने के लिए» OTP बताना — वही तो फ़्रॉड है। यह सही नहीं है।',
      ],
      sambhaal: [
        'साइन से पहले हर लोन पेपर पढ़वा कर सुनें; जो साइन करें उसकी कॉपी रखें।',
        'रिकवरी कॉल और विज़िट का तारीख़ वाला लॉग रखें — नंबर, टाइम, क्या कहा। मैसेज सेव करें।',
        'पहले लेंडर के ग्रीवांस ऑफ़िसर को लिखित शिकायत — इसी से मुफ़्त RBI ओम्बड्समैन की 30-दिन घड़ी शुरू होती है।',
        'उधार लेने से पहले लेंडर सचेत पोर्टल पर चेक करें।',
        'खाते से फ़्रॉड में पैसा निकले तो तुरंत 1930 पर कॉल करें — पहला घंटा सबसे ज़रूरी है।',
      ],
      ekKadam: 'वसूली के हर फ़ोन और आने-जाने का तारीख़ वाला रिकॉर्ड रखें।',
      authority: {
        office: 'लेंडर का ग्रीवांस ऑफ़िसर → 30 दिन बाद RBI ओम्बड्समैन · पुलिस (किसी भी थाने में ज़ीरो FIR) · NBFC-MFI के लिए MFIN',
        askFor: 'ब्रांच ग्रीवांस ऑफ़िसर; थाना प्रभारी',
      },
    },
    hinglish: {
      kanoon: [
        'Pati ke personal loan ki zimmedari patni par apne-aap nahin aati. Contract sirf sign karne waalon ko bandhta hai.',
        'Guarantee tabhi hai jab aapne sach mein guarantor ke taur par sign kiya ho (Contract Act dhara 126) — aur dabav ya dhokhe se liya gaya sign radd karwaya ja sakta hai (dharaein 15–19).',
        'RBI ke niyam banks, NBFCs aur unke recovery agents par laagu hain: call ya visit sirf subah 8 se shaam 7 tak, dhamki ya be-izzati nahin, aur agent ko apna aur company ka naam batana hoga.',
        'Lender ke grievance officer ko likhit shikayat ke 30 din mein hal na ho, toh cms.rbi.org.in par muft shikayat karein. Recovery-agent harassment iski list mein saaf likha hai.',
        'Agent ki dhamki, ghar mein ghusna ya maar-peet loan se alag, seedha police ka mamla hai — 112.',
      ],
      asli: [
        'Blank paper, adhoora form, ya jo padh na sakein — us par kabhi sign nahin. «Bas sign kar do, formality hai» se hi guarantee bana di jaati hai. Yeh sahi nahin hai.',
        '«Sirf kaagaz par» guarantor ya co-borrower banna — zimmedari kaagaz par hi toh rehti hai. Yeh sahi nahin hai.',
        'Kisi aur ke loan ke liye apna Aadhaar aur photo de dena. Yeh sahi nahin hai.',
        'Bachat samooh ka loan aapke naam par aur istemal doosron ka — default aapke record par baithta hai. Yeh sahi nahin hai.',
        'Raat ko call, baar-baar ghar aana, padosiyon ke saamne be-izzati — yeh sab niyam todna hai, aadat nahin. Har ek ki report ho sakti hai. Yeh sahi nahin hai.',
        'Aise loan apps jo contacts aur photos ka access maangein — yeh blackmail ka jaana-pehchaana pattern hai. Yeh sahi nahin hai.',
        '«Loan closure verify karne ke liye» OTP batana — wahi toh fraud hai. Yeh sahi nahin hai.',
      ],
      sambhaal: [
        'Sign se pehle har loan paper padhwa kar sunein; jo sign karein uski copy rakhein.',
        'Recovery call aur visit ka tareekh waala log rakhein — number, time, kya kaha. Messages save karein.',
        'Pehle lender ke grievance officer ko likhit shikayat — isi se muft RBI Ombudsman ki 30-din ghadi shuru hoti hai.',
        'Udhaar lene se pehle lender Sachet portal par check karein.',
        'Khaate se fraud mein paisa nikle toh turant 1930 par call karein — pehla ghanta sabse zaroori hai.',
      ],
      ekKadam: 'Vasooli ke har phone aur aane-jaane ka tareekh waala record rakhein.',
      authority: {
        office: 'Lender ka Grievance Officer → 30 din baad RBI Ombudsman · Police (kisi bhi thane mein Zero FIR) · NBFC-MFI ke liye MFIN',
        askFor: 'Branch Grievance Officer; SHO',
      },
    },
    en: {
      kanoon: [
        'A wife is not automatically liable for her husband\'s personal loan. A contract binds only those who signed it.',
        'A guarantee exists only if she actually signed as guarantor (Contract Act s.126) — and a signature obtained by pressure or fraud can be set aside (ss.15–19).',
        'RBI rules bind banks, NBFCs and their recovery agents: calls and visits only between 8am and 7pm, no threats or humiliation, and the agent must identify himself and his company.',
        'If a written complaint to the lender\'s grievance officer is not resolved within 30 days, complain free at cms.rbi.org.in. Recovery-agent harassment is expressly listed.',
        'Threats, forced entry or assault by an agent are a police matter in their own right, separate from the loan — 112.',
      ],
      asli: [
        'Never sign a blank page, an incomplete form, or anything she cannot read. "Just sign, it\'s a formality" is how a guarantee gets created. This is not right.',
        'Becoming a guarantor or co-borrower "only on paper". Liability lives on paper. This is not right.',
        'Handing over her Aadhaar copy and photograph for someone else\'s loan. This is not right.',
        'A self-help group loan in her name that others use. The default lands on her record. This is not right.',
        'Night calls, repeated house visits, humiliation in front of neighbours. These break the rules; they are not just how it is done, and each can be reported. This is not right.',
        'Loan apps demanding access to contacts and photos. That is a well-known blackmail pattern. This is not right.',
        'Giving an OTP "to verify loan closure". That is the fraud, not the closure. This is not right.',
      ],
      sambhaal: [
        'Have every loan paper read aloud before signing, and keep a copy of whatever is signed.',
        'Keep a dated log of recovery calls and visits — number, time, what was said. Save the messages.',
        'Complain in writing to the lender\'s grievance officer first. That starts the 30-day clock for the free RBI Ombudsman.',
        'Check a lender on the Sachet portal before borrowing.',
        'If money leaves the account through fraud, call 1930 immediately. The first hour matters most.',
      ],
      ekKadam: 'Keep a dated record of every recovery call and visit.',
      authority: {
        office: 'Lender\'s Grievance Officer → RBI Ombudsman after 30 days · Police (Zero FIR at any station) · MFIN for NBFC-MFI borrowers',
        askFor: 'Branch Grievance Officer; SHO',
      },
    },
    numbers: ['14448', '1930', '112', '1800-102-1080'],
    portals: [
      { label: 'cms.rbi.org.in', href: 'https://cms.rbi.org.in' },
      { label: 'sachet.rbi.org.in', href: 'https://sachet.rbi.org.in' },
      { label: 'cybercrime.gov.in', href: 'https://cybercrime.gov.in' },
    ],
  },
};
